apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  namespace: proliga-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      containers:
        - name: postgrest
          image: postgrest/postgrest:latest
          env:
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: proliga-secrets
                  key: PG_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: proliga-secrets
                  key: DB_PASSWORD
            - name: PG_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: proliga-secrets
                  key: PG_DB_NAME
            - name: PGRST_DB_URI
              value: postgres://$(PG_USER):$(DB_PASSWORD)@proliga-pooler.proliga-db.svc.cluster.local:5432/$(PG_DB_NAME)
            - name: PGRST_DB_ANON_ROLE
              value: web_anon
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: proliga-secrets
                  key: PGRST_JWT_SECRET
            - name: PGRST_SERVER_PORT
              value: "3000"
          ports:
            - containerPort: 3000
