# pvc-static.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-assets-pvc
  namespace: test-nginx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
