apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: opensearch
spec:
  general:
    serviceName: my-first-cluster
    version: "3.1.0"
  nodePools:
    - component: nodes
      replicas: 1
      diskSize: "10Gi"
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      roles:
        - cluster_manager
        - data
  initHelper:
    image: docker.io/busybox:1.36
    imagePullPolicy: IfNotPresent
    resources: {}
    version: "1.36"
  security:
    config:
      adminCredentialsSecret:
        name: ""
      adminSecret:
        name: ""
      securityConfigSecret:
        name: ""
      updateJob:
        resources: {}
    tls:
      http:
        caSecret:
          name: ""
        generate: true
        secret:
          name: ""
      transport:
        caSecret:
          name: ""
        generate: true
        perNode: true
        secret:
          name: ""