apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proliga-static-pvc
  namespace: proliga
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
