apiVersion: v1
kind: Service
metadata:
  name: proliga-frontend
  namespace: proliga
spec:
  selector:
    app: proliga-frontend
  ports:
    - name: http
      port: 80        # service port (stable inside cluster)
      targetPort: 3000
  type: ClusterIP
