apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ha-db
spec:
  imageName: ramz001/cnpg:17
  instances: 3

  storage:
    size: 10Gi
    storageClass: longhorn

  postgresql:
    shared_preload_libraries:
      - pg_stat_statements
      - pg_cron
      - pgaudit
      - http
---
apiVersion: v1
kind: Service
metadata:
  name: ha-db-external
  namespace: cnpg-system
spec:
  type: LoadBalancer
  selector:
    cnpg.io/cluster: ha-db
    role: primary
  ports:
    - port: 5432
      targetPort: 5432
