apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-ha
  namespace: postgres
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
